name: Akshaya Jain and Associates
favicon: null
layout_spectrum: 0.2133613396435976
typography_spectrum: 0.779962807893753
title: 'Akshaya Jain & Associates'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.14071578183211386
  lightness: 0.25222198758274317
  saturation: 0.7187027635518461
  rhythmicContrast: 0.6737802904099226
purpose: []
